site_name: multidim-screening
repo_url: https://github.com/bsalanie/multidim-screening
site_url: https://bsalanie.github.io/multidim-screening
site_description: Algorithm to solve for mthe optimal contracts in multidimensional screening problems
site_author: Bernard Salanie
edit_uri: edit/main/docs/
repo_name: bsalanie/multidim-screening

nav:
  - Home: index.md
  - API Reference: 
    - Main: main.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')


# theme:
#   palette:
#     scheme: preference



theme:
  name: material
  features:
    - navigation.instant
    - search.highlight
    - navigation.expand
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bsalanie/multidim-screening
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/multidim-screening

markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
  - toc:
      permalink: true
  - admonition # add notes, warnings...
  - codehilite
  - toc
  - pymdownx.arithmatex: # for LaTeX
      generic: true  
extra_javascript: # for arithmatex
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

